# Generated by Django 3.1.7 on 2021-04-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('INDIA', 'India'), ('AUSTRALIA', 'Australia'), ('ENGLAND', 'England')], max_length=15),
        ),
    ]
