# Generated by Django 3.1.7 on 2021-03-30 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('washable', models.CharField(max_length=5)),
                ('discount', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
