# Generated by Django 3.1.7 on 2021-03-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='washable',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=5),
        ),
    ]
