# Generated by Django 3.1.7 on 2021-04-13 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=20)),
                ('card_type', models.CharField(choices=[('CREDIT CARD', 'Credit card'), ('DEBIT CARD', 'Debit card')], max_length=20)),
                ('expiration', models.CharField(max_length=10)),
                ('card_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
