# Generated by Django 3.1.7 on 2021-04-13 10:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_auto_20210406_0539'),
        ('customer', '0002_auto_20210409_2131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_delivered', models.DateField(default=datetime.datetime(2021, 4, 20, 10, 42, 36, 547655))),
                ('previous_orders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cart')),
                ('user_address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='customer.address')),
                ('user_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
