# Generated by Django 3.1.7 on 2021-04-21 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_delivered', models.DateField(default=datetime.datetime(2021, 4, 28, 10, 25, 33, 387304))),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.IntegerField(default=0)),
                ('address', models.CharField(default='please enter address', max_length=40)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
